### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by tayrosby** [tayrosby/sales-app#12]

**Comment by ZacharyDRobbins** [comment]
This is a link to the ER diagram in Lucid Chart. Accessing through this link can allow editing of the diagram. Leave a comment in this issue with any changes made to the diagram.

https://www.lucidchart.com/invitations/accept/e90d6617-e146-4b78-bdd6-5e211c0ceaf3

**Comment by ZacharyDRobbins** [comment]
We will work out the Diagram in lucid chart and the final ER will be made in mySQL workbench.

**Comment by MSillanp** [comment]
Added some basic entities on to the table - WIP

**Comment by MSillanp** [comment]
Added in "category" function, issue should be complete
