### ISSUE TITLE
Create issues for client questions

### ISSUE THREAD

**Issue by JoshVandeWalle** [tayrosby/sales-app#2]

**Comment by tayrosby** [comment]
Should we be hosting this application to a cloud solution?

**Comment by ZacharyDRobbins** [comment]
Is this application supposed to be themed to sell a specific type of product(s) or is it supposed to be a more general approach like amazon or ebay?

**Comment by MSillanp** [comment]
Scope: Calculate sales tax based of zip code

**Comment by JoshVandeWalle** [comment]
Scope: Email notifications have the potential to cause massive disruption to the schedule, and can be integrated at a later time if time allows. It also seems beyond the scope of a typical sales application

**Comment by ausstinh** [comment]
Allow bootstrap framework to be implemented? If so, specific template/layout requirements?

**Comment by OrlandoPDL** [comment]
Is 'ability to share items with others' requirement needed as users could send the urls to other users without us needing to implement a system to send other users products

**Comment by pyin910614** [comment]
How will we simulate credit and PayPal payment?
