### ISSUE TITLE
Metrics and Discussion

### ISSUE THREAD

**Issue by ZacharyDRobbins** [tayrosby/sales-app#31]

**Comment by ausstinh** [comment]
I will do response time for logging in, registering, adding to cart, ect.

**Comment by JoshVandeWalle** [comment]
I will do module statuses. So every module goes in a category based on completeness.

**Comment by JoshVandeWalle** [comment]
I will do beta tester reviews as a quality metric.

**Comment by tayrosby** [comment]
I am doing a metric comparing the original requirements list and the implemented requirements

**Comment by OrlandoPDL** [comment]
I'm doing average time between system failures
