### ISSUE TITLE
Software Upgrades and Bug Fixes

### ISSUE THREAD

**Issue by tayrosby** [tayrosby/sales-app#34]

**Comment by MSillanp** [comment]
https://docs.google.com/spreadsheets/d/1VlSCXv4tt2o7biUujvBN-UiuDrbTgjL-0dbUJYq4Q1U/edit#gid=0

**Comment by MSillanp** [comment]
Moved the schedule chart onto a word doc for the whole section located under CST-326 Sales App>Software Maintenance Plan >Software Update Model and Schedule
