### ISSUE TITLE
Vision Statement

### ISSUE THREAD

**Issue by tayrosby** [tayrosby/sales-app#9]
The team will discuss whether we will use the mission statement from the previous sprint as the vision statement or come up with a new vision statement. The assignee will be in charge of adding the vision statement to the document.

**Comment by JoshVandeWalle** [comment]
Here is what I have. I can change it if there are problems. Vision statements are usually short so I kept this focused on our main goals. 

Vision Statement
	Our company is developing and marketing a web marketplace program that small businesses can use to facilitate their e-commerce operations. Our program allows businesses that would otherwise be unable to develop such a program to compete in the lucrative online commerce industry against technology giants such as Amazon. To ensure our clients satisfaction, we are developing our program with the goal of turning out a product that is both fully functional and user-friendly. Our ultimate goal is to create a program that meets the needs of both our clients and our end users.

**Comment by JoshVandeWalle** [comment]
New version:

Vision Statement
	Our company is developing a web marketplace where users can buy and sell items. Sellers will put items up for sale and buyers will search available items for their desired products. We aim to provide buyers and sellers with an application that is easy to use, fully functional, and free from major defects. People everywhere have things to sell and items they wish to purchase. Our company’s goal is to help people help people.
